services:
    netgen.ibexa_site_api.routing.generator_router:
        class: Netgen\Bundle\IbexaSiteApiBundle\Routing\GeneratorRouter
        arguments:
            - '@ibexa.api.repository'
            - '@Ibexa\Core\MVC\Symfony\Routing\Generator\UrlAliasGenerator'
            - '@netgen.ibexa_site_api.siteaccess.resolver'
            - '@router.request_context'
        tags:
            - { name: router, priority: 300 }
        lazy: true
